### ISSUE TITLE
Need installation instructions

### ISSUE THREAD

**Issue by obilodeau** [GoSecure/zap-autodecode-view#4]
At least a pointer to them

**Comment by obilodeau** [comment]
copy in plugin folder under this: https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/

**Comment by obilodeau** [comment]
or load add-on in the file dialog?

**Comment by h3xstream** [comment]
Added https://github.com/GoSecure/zap-autodecode-view#tutorials
